name: Build and deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug - List directory contents
      run: ls -R

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.x'  # Replace with your .NET version

    - name: Restore dependencies
      run: dotnet restore ./nlphelpdesk.sln

    - name: Build and publish
        run: dotnet publish nlphelpdesk/nlphelpdesk.csproj --configuration Release --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: nlphelpdesk-v-1
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish