name: Build and deploy Azure Function to Azure Function App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.x'

    - name: Restore dependencies
      run: |
        dotnet restore

    - name: Build the function
      run: |
        dotnet build --configuration Release

    - name: Publish the function
      run: |
        dotnet publish --configuration Release --output ./publish

    - name: Deploy to Azure Function App
      uses: azure/webapps-deploy@v2
      with:
        app-name: nlphelpdesk-function
        publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE }}
        package: ./publish